version: "3.5"

services:

  hello-banker-api:
    image: wenkatn/hello-banker-api:latest
    container_name: hello-banker-api
    ports:
      - '8989:8989'
    networks:
      - hello-banker
    
  hello-banker-web:
    image: wenkatn/hello-banker-web:latest
    container_name: hello-banker-web
    ports:
      - '8988:80'
    depends_on:
      - hello-banker-api
    networks:
        - hello-banker

networks:
    hello-banker:
      name: hello-banker